"""Parameters adapted from the original HOPPY MATLAB simulator.

This version is tuned so the HOPPY keeps the correct compact leg pose while
making forward progress around the boom yaw axis.
Units are SI unless stated otherwise.
"""
from __future__ import annotations

import numpy as np

# Simulation
DT = 0.001
GRAVITY = 9.81
RBOOM = 556.0e-3
T_STANCE = 0.122

# Initial condition: compact pose with the real foot pad close to the floor.
Q0 = {
    "joint1": 0.0,
    "joint2": 0.010,
    "joint3": 0.0,
    "joint4": 0.0,
}

# Desired circular motion around the gantry.
# +1 produces counter-clockwise yaw in MuJoCo world coordinates, -1 reverses it.
CIRCLE_DIRECTION = -1.0
TARGET_YAW_RATE = 0.58          # rad/s, quicker circular locomotion
TANGENTIAL_FORCE_FF = 78.0      # N feed-forward horizontal GRF
KP_YAW_VEL = 155.0              # N per (m/s) tangential speed error
MAX_TANGENTIAL_FORCE = 175.0    # N

# Flight controller / foot placement
KP_SW = np.diag([50.0, 50.0, 138.0])
KD_SW = np.diag([3.8, 3.8, 10.6])
FOOT_CLEARANCE_FROM_HIP = 0.165
FLIGHT_SWING_LIFT = 0.092
FLIGHT_TANGENTIAL_OFFSET = 0.036
FLIGHT_TOUCHDOWN_TANGENTIAL_OFFSET = 0.012
FLIGHT_RADIAL_OFFSET = 0.030
FLIGHT_TOUCHDOWN_RADIAL_OFFSET = 0.020

# Stance controller: moderate extension through mid-stance, then retract for
# the next touchdown instead of getting stuck in an over-open pose.
KP_ST = np.array([44.0, 56.0])
KD_ST = np.array([4.2, 5.4])
Q_D_STANCE = np.array([0.05, 0.08])
Q_D_PUSH = np.array([0.37, 0.33])
Q_D_RETRACT = np.array([0.22, 0.18])
FZ_BEZIER = np.array([0.0, 360.0, 920.0, 460.0, 0.0])

# Foot hold: hold the contact point during stance, but do not fight the desired
# tangential propulsion.  We only apply a small correction in the radial direction.
KP_FOOT_HOLD_RADIAL = 420.0
KD_FOOT_HOLD_RADIAL = 24.0
MAX_FOOT_HOLD_RADIAL_FORCE = 24.0

# Soft anti-collapse support during stance.  When the foot height drops too
# low, inject some extra vertical support so the leg does not flatten out
# against the ground before push-off.
STANCE_TOE_Z_SOFT_MIN = 0.040
KP_STANCE_HEIGHT = 9500.0
KD_STANCE_HEIGHT = 370.0
MAX_STANCE_HEIGHT_FORCE = 175.0

# Motor / reducer data from get_params.m
NH = 26.9
NK = 28.8
I_ROTOR = 7.0e-6
RW = 1.3
KT = 0.0135
KV = 0.0186

HIP_ARMATURE = I_ROTOR * NH**2
KNEE_ARMATURE = I_ROTOR * NK**2
HIP_DAMPING = KV * KT * NH**2 / RW
KNEE_DAMPING = KV * KT * NK**2 / RW

# MATLAB spring torque: tau_s = -0.0242*q_knee + 0.0108, then applied as 2*tau_s.
KNEE_STIFFNESS = 2.0 * 0.0242
KNEE_SPRINGREF = 0.0108 / 0.0242

# Torque saturation.  This is explicit in the controller and mirrored in MJCF.
HIP_TORQUE_LIMIT_NM = 20.0
KNEE_TORQUE_LIMIT_NM = 20.0
HIP_LIMIT_A = np.array([[0.0, 1.0], [0.0, -1.0]])
HIP_LIMIT_B = np.array([HIP_TORQUE_LIMIT_NM, HIP_TORQUE_LIMIT_NM])
KNEE_LIMIT_A = np.array([[0.0, 1.0], [0.0, -1.0]])
KNEE_LIMIT_B = np.array([KNEE_TORQUE_LIMIT_NM, KNEE_TORQUE_LIMIT_NM])

# Encoder emulation
ENCODER_COUNTS_PER_REV = 4096
ENCODER_QUANTIZATION = 2.0 * np.pi / ENCODER_COUNTS_PER_REV
LOWPASS_ALPHA = 0.18

# Contact/event thresholds
TOUCHDOWN_FORCE_N = 0.5
LIFTOFF_FORCE_N = 0.25
MIN_STANCE_TIME = 0.105
MAX_STANCE_TIME = 0.175
MIN_FLIGHT_TIME = 0.24

# Pose reset so the foot does not stay hanging after a hop.
KP_FLIGHT_POSTURE = np.array([92.0, 104.0])
KD_FLIGHT_POSTURE = np.array([7.0, 7.5])
Q_D_FLIGHT = np.array([-0.16, -0.10])

# Small pitch guide on the passive boom DOF.  In flight we bias the boom
# slightly upward so the leg can actually clear the floor; in stance we relax
# it closer to level so the foot can still load and propel around the circle.
PITCH_GUIDE_ENABLE = True
PITCH_GUIDE_TARGET_FLIGHT = -0.100
PITCH_GUIDE_TARGET_STANCE = -0.008
PITCH_GUIDE_KP = 82.0
PITCH_GUIDE_KD = 9.8
PITCH_GUIDE_MAX_TORQUE = 20.0

# Small passive-yaw guide.  This should only bias the preferred direction,
# not replace the locomotion generated by the leg.
YAW_GUIDE_ENABLE = True
YAW_GUIDE_TARGET_RATE = -0.36
YAW_GUIDE_KD = 7.0
YAW_GUIDE_MAX_TORQUE = 5.0
